### PR TITLE
Implemented filtering for the Armor List

### PR DESCRIPTION
**Pull request by zachdayz**
One problem, however: the text on the filter dialog appears white - for whatever reason, the app style doesn't seem to get applied to it

### CODE REVIEW

**Comment by zachdayz** [comment]
I worked on it more today and the spinners are completely functional.
Furthermore, you can now sort by slot count.

**Comment by kamegami13** [comment]
The popup menu is messed up. I can barely make any changes or read it.

Probably don't need to call it Filter Armor, Filter would be sufficient.

**Comment by zachdayz** [comment]
Yo, I think I fixed the problems with the dialog.

**Comment by kamegami13** [comment]
Awesome, I'll look at this tonight. I gotta head out to family stuff.

**Comment by kamegami13** [comment]
everything looks good

**Pull request merged**
