### PR TITLE
I made an armor set builder.

### PR DESCRIPTION
**Pull request by zachdayz**
Well, at least the framework for one. Currently, it allows you to select and put pieces on a menu. It is extensible, however, seeing as it uses the app's base `Armor` class. I intend to add a skill viewer, as well as perhaps additional sorting options for the piece search.

I should note that the method to start the builder is not built into the app - just copy this code snippet on some sort of `ClickListener` or whatever in the app.

    Intent i = new Intent(getApplicationContext(), ArmorSetBuilderActivity.class);
    startActivity(i);

### CODE REVIEW

**Comment by jaysonthepirate** [comment]
This looks pretty cool! Am I right in assuming we're not storing any of the armor configuration data? Users are building the entire set from scratch every time?

I haven't had time to test this but it looks like the framework let you select pieces of armor to form a set, but it doesn't pull skills or let you set decorations yet. Are you still working on this or are you waiting for this pull to go through?

**Comment by zachdayz** [comment]
Yeah, I haven't gotten to work on storing any data. I haven't really even looked into that, but I figured that user sets would be stored similarly to Wishlists.
I'm working on getting skills done now, but I suppose we might as well wait until it's at least functional in that respect before we go about implementing it.

**Comment by jaysonthepirate** [comment]
Ok. I'm ok merging this if Kamegami is. You should join us on Slack so we can organize work better. Has Kamegami sent you an invite? I can if you need one.

**Comment by zachdayz** [comment]
I don't think I've received one yet. Thanks so much!

**Pull request merged**
