### PR TITLE
Logo swap and support library additions.

### PR DESCRIPTION
**Pull request by jaysonthepirate**
Swapped in new MH4U logo and added some v7 support libraries to the build.gradle.

### CODE REVIEW

**Comment by jaysonthepirate** [comment]
Its also my first time playing with Git so I got confused and undid my undo, then undid it.

**Comment by kamegami13** [comment]
Thanks, I'll look at this pull sometime today.

Kamegami

**Comment by kamegami13** [comment]
Any chance you could divide this into two pulls? If that's too much work I'll accept it anyways, but I do need to confirm the actionbar work before I merge.

The logos need to be resized. The logo is far too big for all of the dpi levels and will eat up memory. Use the 3U logos as a guideline of how big they should be.

I haven't tried running the drawer changes you made. Do they still allow you to directly link from one view to the next? i.e. I press on a material for a weapon and get the material page then I click on the monster that drops the material for the monster page. Pressing back button takes me back through these pages. This behavior is critical.

Also, are you moving the ActionBarSherlock to AppCompat? I can't tell from looking on Github I know someone was working on that.

Oh, and I realized that this action bar is a really good place to add universal search. Adding that to Trello.

Sorry for all the critique, awesome work!!

**Comment by jaysonthepirate** [comment]
I'll try to resize the logos tonight.

So this pull basically changed the logo, added a string to the strings file, then added some support libraries. I undid the changes related to the navigation drawer awaiting the migration to AppCompat.

Yes the drawer, if implemented correctly, should maintain the back stack. The click-through navigation should work independent of the navigation drawer.

I was looking into migrating to AppCompat myself but I'm not familiar enough with actionbarsherlock and this app to do it without breaking everything.

**Comment by jaysonthepirate** [comment]
I resized the logos. Let me know how it looks.

**Comment by kamegami13** [comment]
xxdpi still needs to be resized. Everything else looks great. Go ahead and make another pull for that one change.

**Pull request merged**
