### PR TITLE
Draw Sharpness Procedurally

### PR DESCRIPTION
**Pull request by jaysonthepirate**
Draw sharpness works now. On higher DPI devices the entire drawable should be 500x50px max, but should scale down on lower DPI.

The assumption at the moment is that the maximum sharpness possible is 50 units.
nexus 6 detail
nexus 6 list
nexus s detail
nexus s list

### CODE REVIEW

**Comment by kamegami13** [comment]
I'll check this out when I get home in an hour or so. Looks really awesome. Out of curiosity what did you use for test data?

**Comment by jaysonthepirate** [comment]
The existing database has sharpness data from MH3U that works fine. It's in the weapons table under sharpness. The format is "1.2.3.4.5.6.7 1.2.3.4.5.6.7" where each integer is the sharpness value for a particular color. Is the 4U sharpness data similar?

**Comment by kamegami13** [comment]
https://docs.google.com/document/d/1DFWcsKCllUAjaCq8v5ykwNm7bZsDx1uDcJmW_GCMD0Q/edit

I changed it to a separate column for each color. I'm guessing that would
be a simple change on your own. I'm assuming these match the Wikia
sharpness from 3U?

**Comment by jaysonthepirate** [comment]
Yea the data was correct. If you have the data I'd prefer it to be in the String format because there is there are already adapter methods to grab that data from the table. I'm fine either way.

**Comment by kamegami13** [comment]
That would actually be a simple conversion in excel TBH. So sure we can do
that. I actually never bothered to check if the 3U sharpness data was at
all accurate or well formatted.

**Comment by kamegami13** [comment]
Oh, quick thought. Does it handle malformed input without crashing?

**Comment by jaysonthepirate** [comment]
No, right now it's looking for that specific formatted string. Should I be worried about that?

**Comment by kamegami13** [comment]
I'd prefer if it logged an error and returned a blank sharpness bar or
something. Basically I'd prefer if all our code logged an error and handled
it without throwing an exception to avoid crashes.

**Comment by jaysonthepirate** [comment]
Sure I'll try to implement that this weekend.

**Pull request closed without merging**
